# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:


[global]
# general
  name: fpkg-vault   # name displayed in web ui
  name-url: /
  ansi               # enable colors in log messages (both in logfiles and stdout)
  usernames
  ls: *,*,ln,p,r     # https://copyparty.eu/cli/#ls-help-page

# file and multimedia management
  e2dsa             # enable file indexing and filesystem scanning
  e2ts              # enable multimedia indexing
  # e2tsr  # reset multimedia index and rescan
  re-maxage: 3600   # rescan fs for changes every N seconds

# fpkg vault
  on404: /handlers/fpkg_vault.py
  on403: /handlers/fpkg_vault.py
  mte: +type,category,title,title_id,content_id,app_ver,version,system_ver
  mtp: type,category,title,title_id,content_id,app_ver,version,system_ver=ad,epkg,c1,f,/handlers/fpkg_vault.py
  th-extract: pkg=/handlers/fpkg_vault.py
  js-browser: /__fpkgv/script.js
  css-browser: /__fpkgv/style.css
  # th-extr-cv: *    # this feature isn't merged yet https://github.com/9001/copyparty/pull/1616

[accounts]
  user1:password1

[/]
  /w
  accs:
    A: user1
